Repository googleapis/google-api-java-client, pull requests merged in 2020-09, with the labels that each got.

#1576 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#1577 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#1578 chore: add settings sync, cleanup CODEOWNERS
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: cla: yes

#1587 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1590 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#1591 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1593 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
