Repository googleapis/google-api-java-client, pull requests merged in 2020-12, with the labels that each got.

#1645 deps: update Guava to 30.0
  pom.xml
Labels: cla: yes

#1652 docs: Update the documentation link for GoogleCredential from deprecated version to newer version
  docs/oauth-2.0.md
Labels: cla: yes

#1651 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1655 chore(docs): Update code snippets to use newer version of GoogleCredentials
  docs/oauth-2.0.md
Labels: api: docs, automerge, cla: yes

#1657 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1659 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge
