Repository googleapis/google-api-java-client, pull requests merged in 2020-11, with the labels that each got.

#1615 chore: delete TravisCI config
  .travis.yml
Labels: cla: yes

#1624 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1627 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1619 feat: add mtls support to GoogleNetHttpTransport and GoogleApacheHttpTransport
  google-api-client/src/main/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransport.java
  google-api-client/src/main/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.java
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/ContextAwareMetadataJson.java
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/MtlsProvider.java
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/MtlsUtils.java
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/package-info.java
  google-api-client/src/main/java/com/google/api/client/googleapis/util/Utils.java
  google-api-client/src/test/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransportTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransportTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/mtls/MtlsTransportBaseTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/mtls/MtlsUtilsTest.java
  google-api-client/src/test/resources/com/google/api/client/googleapis/util/mtlsCertAndKey.pem
  google-api-client/src/test/resources/com/google/api/client/googleapis/util/mtls_context_aware_metadata.json
  google-api-client/src/test/resources/com/google/api/client/googleapis/util/mtls_context_aware_metadata_bad_command.json
Labels: automerge, cla: yes

#1636 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1637 fix: socketfactory not registered for apache
  google-api-client/src/main/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransport.java
  google-api-client/src/test/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransportTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/mtls/MtlsTransportBaseTest.java
Labels: cla: yes

#1643 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1646 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1647 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: automerge, cla: yes, context: full, samples
