Repository googleapis/google-api-java-client, pull requests merged in 2021-09, with the labels that each got.

#1870 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, automerge

#1879 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes

#1877 chore: update java-docfx-doclet version
  pom.xml
Labels: cla: yes

#1884 chore: remove java7 from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#1885 chore: java 7 units check
  .github/workflows/ci.yaml
Labels: cla: yes, automerge

#1886 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#1887 chore: change branch master to main in github configurations
  .github/workflows/ci.yaml
Labels: cla: yes, automerge
