Repository googleapis/google-api-java-client, pull requests merged in 2021-03, with the labels that each got.

#1735 ci: removing Kokoro from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#1739 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1743 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1738 fix: re-encode public keys from google.jks into p12 format for android
  google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java
  google-api-client/src/main/resources/com/google/api/client/googleapis/google.p12
Labels: cla: yes

#1745 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1749 fix: wrap BatchRequest InputStream with BufferedInputStream
  google-api-client/src/main/java/com/google/api/client/googleapis/batch/BatchRequest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestStressTest.java
Labels: automerge, cla: yes

#1754 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: build.sh, cla: yes, context: full, in, sample-secrets, samples

#1756 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
