Repository googleapis/google-api-java-client, pull requests merged in 2021-11, with the labels that each got.

#1918 chore: cleanup cloud RAD generation
  pom.xml
Labels: cla: yes, automerge

#1921 chore: fix owlbot image
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes

#1917 chore: cleanup javadoc code comments
  google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/gms/auth/GooglePlayServicesAvailabilityIOException.java
  google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/gms/auth/UserRecoverableAuthIOException.java
  google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java
  google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/notifications/AppEngineNotificationServlet.java
  google-api-client-gson/src/main/java/com/google/api/client/googleapis/notifications/json/gson/GsonNotificationCallback.java
  google-api-client-jackson2/src/main/java/com/google/api/client/googleapis/notifications/json/jackson2/JacksonNotificationCallback.java
  google-api-client-protobuf/src/main/java/com/google/api/client/googleapis/services/protobuf/AbstractGoogleProtoClientRequest.java
  google-api-client-protobuf/src/main/java/com/google/api/client/googleapis/services/protobuf/CommonGoogleProtoClientRequestInitializer.java
  google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/NotificationServlet.java
  google-api-client-xml/src/main/java/com/google/api/client/googleapis/xml/atom/AtomPatchContent.java
  google-api-client-xml/src/main/java/com/google/api/client/googleapis/xml/atom/AtomPatchRelativeToOriginalContent.java
  google-api-client-xml/src/main/java/com/google/api/client/googleapis/xml/atom/package-info.java
  google-api-client/src/main/java/com/google/api/client/googleapis/MethodOverride.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeRequestUrl.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeTokenRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleBrowserClientRequestUrl.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleClientSecrets.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleRefreshTokenRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/batch/BatchCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/batch/BatchRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/batch/json/JsonBatchCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/compute/ComputeCredential.java
  google-api-client/src/main/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.java
  google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonError.java
  google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonResponseException.java
  google-api-client/src/main/java/com/google/api/client/googleapis/json/package-info.java
  google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloaderProgressListener.java
  google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java
  google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploaderProgressListener.java
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/ContextAwareMetadataJson.java
  google-api-client/src/main/java/com/google/api/client/googleapis/notifications/TypedNotificationCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/notifications/UnparsedNotificationCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/notifications/json/JsonNotificationCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/CommonGoogleClientRequestInitializer.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/GoogleClientRequestInitializer.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/json/AbstractGoogleJsonClientRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/services/json/CommonGoogleJsonClientRequestInitializer.java
Labels: kokoro:force-run, cla: yes
