Repository googleapis/google-api-java-client, pull requests merged in 2021-05, with the labels that each got.

#1782 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#1785 fix: remove deprecated parent pom
  pom.xml
Labels: cla: yes

#1787 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1783 fix: update GoogleJsonError object to accomodate all fields in Invalid parameter exception
  google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonError.java
  google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonResponseExceptionTest.java
  google-api-client/src/test/resources/com/google/api/client/googleapis/json/error.json
Labels: automerge, cla: yes

#1793 build: add developer field to parent pom
  pom.xml
Labels: automerge, cla: yes

#1796 feat: configure initial sp version
  .github/workflows/ci.yaml
  google-api-client-protobuf/pom.xml
  google-api-client/pom.xml
  pom.xml
Labels: cla: yes

#1786 chore: remove codecov
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  codecov.yaml
  synth.metadata
Labels: cla: yes

#1805 build: switch all clients to use the google endpoint on sonatype
  google-api-client-bom/pom.xml
  pom.xml
Labels: cla: yes

#1809 chore: Re-generated to pick up changes from synthtool
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  .kokoro/release/publish_javadoc11.sh
  codecov.yaml
  synth.metadata
Labels: cla: yes, context: partial

#1811 chore: update cloud-rad doclet
  pom.xml
Labels: cla: yes

#1813 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1815 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
