Repository googleapis/google-api-java-client, pull requests merged in 2021-04, with the labels that each got.

#1762 deps: update guava
  pom.xml
Labels: cla: yes

#1770 build: update protobuf plugin
  google-api-client-protobuf/pom.xml
  google-api-client/pom.xml
  pom.xml
Labels: automerge, cla: yes

#1769 fix: release scripts from issuing overlapping phases
  .kokoro/build.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1775 chore: add cloud-rad doc generation
  pom.xml
Labels: cla: yes
