Repository googleapis/google-api-java-client, pull requests merged in 2021-01, with the labels that each got.

#1661 fix: use Gson instead of Jackson
  google-api-client-appengine/src/test/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredentialTest.java
  google-api-client-jackson2/src/main/java/com/google/api/client/googleapis/notifications/json/jackson2/JacksonNotificationCallback.java
  google-api-client/pom.xml
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeTokenRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleRefreshTokenRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/json/package-info.java
  google-api-client/src/main/java/com/google/api/client/googleapis/notifications/TypedNotificationCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/notifications/json/JsonNotificationCallback.java
  google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockGoogleCredential.java
  google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockTokenServerTransport.java
  google-api-client/src/main/java/com/google/api/client/googleapis/testing/compute/MockMetadataServerTransport.java
  google-api-client/src/main/java/com/google/api/client/googleapis/util/Utils.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProviderTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeFlowTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeTokenRequestTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredentialTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifierTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GooglePublicKeysManagerTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/compute/ComputeCredentialTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorContainerTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/json/AbstractGoogleJsonClientTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/json/CommonGoogleJsonClientRequestInitializerTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/testing/json/GoogleJsonResponseExceptionFactoryTestingTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/util/UtilsTest.java
Labels: cla: yes

#1658 deps: update Guava to 30.1
  pom.xml
Labels: automerge, cla: yes

#1664 fix: remove unused code
  google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestTest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/util/UtilsTest.java
Labels: automerge, cla: yes

#1673 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1674 build: migrate to flakybot
  .kokoro/build.sh
Labels: automerge, cla: yes
