Repository googleapis/google-api-java-client, pull requests merged in 2022-01, with the labels that each got.

#1945 chore: keep clirr-ignored-differences
  clirr-ignored-differences.xml
  owlbot.py
Labels: kokoro:force-run, automerge, owlbot:ignore

#1957 chore: update release-levels in .repo-metadata.json
  .repo-metadata.json
Labels: kokoro:force-run, owlbot:ignore

#1962 chore: update cloud rad doclet
  pom.xml
Labels: kokoro:force-run, automerge
