Repository googleapis/google-api-java-client, pull requests merged in 2022-11, with the labels that each got.

#2179 feat: next release from main branch is 2.1.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#2180 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: size: l

#2195 fix: update and declare commons-codec dependency
  pom.xml
Labels: size: xs
