Repository googleapis/google-api-java-client, pull requests merged in 2022-04, with the labels that each got.

#2034 feat: deprecate OOB auth flow in GooglePromptReceiver
  google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/GooglePromptReceiver.java
Labels: size: xs

#2035 deps: revert protobuf to 3.19
  pom.xml
Labels: size: xs

#2042 feat: next release from main branch is 1.35.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, size: s

#2043 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: automerge, size: l

#2053 deps: downgrade appengine to 1.9.X
  pom.xml
Labels: size: xs
