Repository googleapis/google-api-java-client, pull requests merged in 2023-01, with the labels that each got.

#2210 fix: Make Details field extends GenericJson so that GoogleJsonError should include any arbitrary error info from services
  google-api-client/pom.xml
  google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonError.java
  google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorTest.java
  google-api-client/src/test/resources/com/google/api/client/googleapis/json/errorResponseWithMultipleTypesInDetails.json
  google-api-client/src/test/resources/com/google/api/client/googleapis/json/expectedParsedErrorWithMultipleTypesInDetails.json
  pom.xml
Labels: cla: yes, size: m

#2227 fix: media upload to have applicationName as User-Agent
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientTest.java
Labels: size: m

#2230 build: RenovateBot shouldn't touch requirements.txt
  renovate.json
Labels: size: xs

#2244 docs: adding deprecated annotation for OOB flow and guide for migration
  google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/GooglePromptReceiver.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleOAuthConstants.java
Labels: size: s

#2242 feat: remove deprecated OOB flow
  docs/component-modules.md
  google-api-client-assembly/classpath-include
  google-api-client-assembly/pom.xml
  google-api-client-bom/pom.xml
  google-api-client-java6/pom.xml
  google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/GooglePromptReceiver.java
  google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/package-info.java
  google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleOAuthConstants.java
  pom.xml
Labels: size: m
