Repository googleapis/google-api-java-client, pull requests merged in 2023-07, with the labels that each got.

#2337 ci: revert maven wrapper workaround for CI/Windows check
  .github/workflows/ci.yaml
Labels: size: xs

#2341 feat: setup 2.2.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#2342 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: size: l
