Repository googleapis/google-api-java-client, pull requests merged in 2024-08, with the labels that each got.

#2503 feat: Provide HttpTransport support for google certificates with apache HTTP client v5 (#2497)
  docs/component-modules.md
  google-api-client-apache-v5/pom.xml
  google-api-client-apache-v5/src/checkstyle/checkstyle-suppressions.xml
  google-api-client-apache-v5/src/main/java/com/google/api/client/googleapis/apache/v5/GoogleApache5HttpTransport.java
  google-api-client-apache-v5/src/main/java/com/google/api/client/googleapis/apache/v5/package-info.java
  google-api-client-apache-v5/src/test/java/com/google/api/client/googleapis/apache/v5/GoogleApache5HttpTransportTest.java
  google-api-client-apache-v5/src/test/java/com/google/api/client/googleapis/apache/v5/ITGoogleApache5HttpTransportTest.java
  google-api-client/pom.xml
  google-api-client/src/main/java/com/google/api/client/googleapis/mtls/MtlsProvider.java
  google-api-client/src/test/java/com/google/api/client/googleapis/mtls/MtlsTransportBaseTest.java
  pom.xml
Labels: size: l

#2506 feat: fixed missing version update for new pom file
  google-api-client-apache-v5/pom.xml
Labels: size: xs

#2508 chore: remove owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  codecov.yaml
  owlbot.py
  synth.metadata
Labels: size: m
