Repository googleapis/google-api-java-client, pull requests merged in 2024-05, with the labels that each got.

#2462 feat: Add ApiVersion Support
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
  google-api-client/src/main/java/com/google/api/client/googleapis/testing/services/MockGoogleClientRequest.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
Labels: size: m

#2467 fix: Update ApiVersion Header Typo
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
Labels: size: xs

#2477 deps: downgrading guava version to 33.1.0 for consistency
  pom.xml
  renovate.json
Labels: size: s

#2484 feat: WebHookUtil classes using the jakarta namespace
  google-api-client-servlet/pom.xml
  google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/NotificationServlet.java
  google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/WebhookUtils.java
  google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/package-info.java
  pom.xml
Labels: size: l

#2487 chore: pinning jakarta servlet API v5
  renovate.json
Labels: size: xs
