Repository googleapis/google-api-java-client, pull requests merged in 2024-03, with the labels that each got.

#2435 feat: Add Universe Domain Support
  .github/workflows/ci.yaml
  google-api-client/pom.xml
  google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java
  google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientTest.java
  pom.xml
Labels: size: l

#2445 docs: latest libraries-bom
  docs/setup.md
Labels: size: xs

#2456 docs: Update README.md to point to the current documentation page
  README.md
Labels: size: xs

#2459 chore: update DocFX profile and remove obsolete kokoro configs
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/bump_snapshot.sh
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  owlbot.py
  pom.xml
Labels: size: xl
