Repository googleapis/google-api-java-client, pull requests merged in 2025-05, with the labels that each got.

#2581 chore: add unit tests again runtime JDK 24
  .github/workflows/ci.yaml
Labels: size: s

#2582 chore: update truststore to contain DigiCert Global Root G2
  google-api-client/src/main/resources/com/google/api/client/googleapis/google.p12
  google-api-client/src/test/java/com/google/api/client/googleapis/GoogleUtilsTest.java
Labels: size: xs

#2585 ci: wrap nexus-staging-maven-plugin in a profile
  google-api-client-bom/pom.xml
  pom.xml
Labels: size: m
